### ISSUE TITLE
REST Wrapper

### ISSUE THREAD

**Issue by johnmara** [josemmo/einvoicing#1]
Since you do something really helpful for anyone who wants to start with e-invoicing, it would be useful to provide REST enpoints for people who are not familiar with php like me. For example, I want to use it in a java project.
Maybe it's in the scope of this project since you want to create a php library but it could be a familiar project.

**Comment by josemmo** [comment]
Creating a REST API was not one of my goals with this project but I guess it's something useful that could be implemented in the long term.

What did you have in mind?

**Comment by johnmara** [comment]
Sorry, I read again my answer and I had a typo. I wanted to say 

> Maybe it's **not** in the scope

Once I have the necessary time, I will start playing with php and build a RESTful Web service(maybe Laravel as I read) that uses your library in the backend and exposes endpoints for creating an invoice (parameters of invoice in json format) and return the generated xml.

**Comment by josemmo** [comment]
Closed due to inactivity
