### ISSUE TITLE
UXML get returns self|null ...

### ISSUE THREAD

**Issue by rycks** [josemmo/einvoicing#16]
Hello,
with a "bad" XML file this bug could happens:

```
Call to a member function asText() on null", "exception": "Error", "file": "vendor/josemmo/einvoicing/src/Readers/UblReader.php", "line": 61
```

Because of get function in UXML.php returns self or null

So i could make a fix but i don't know if the best solution is to return an empty object instead off null or add a test on each ->get call ?

For example

Solution 1 in UXML.php could become

```

    /**
     * Find one element
     * @param  string    $xpath XPath query relative to this element
     * @return self|empty object        First matched element or empty object if not found
     */
    public function get(string $xpath): ?self {
        $res = $this->getAll($xpath, 1);
        return $res[0] ?? new UXML();
    }

```

Or Solution 2 will be to change every (like in UblReader.php line 61 and all others)

```
            $rate = (float) $node->get("{{$cbc}}Percent")->asText();
```

to

```

if(isset($node->get("{{$cbc}}Percent"))) {
            $rate = (float) $node->get("{{$cbc}}Percent")->asText();
}

```

**Comment by rycks** [comment]
Hmmm self update, Solution 1 can't be used ! so i start to test all get returns before accessing to supposed values ...

**Comment by josemmo** [comment]
Hello @rycks,

UXML is a different library, `UXML::get()` must return `null` if no element is found as per the specification. So yeah, that cannot be changed.

The PR you propose isn't possible either as none of the values you've changed can be `null` (eInvoicing expects them to be non empty). Probably adding a few `null` checks and throwing an `InvalidArgumentException` is the best approach here given it will comply with the [current documentation](https://josemmo.github.io/einvoicing/reference/ubl-reader/), which would be ideal for backward compatibility.

Will that fit your use case? I'm assuming you're parsing an XML document that doesn't comply with the UBL PEPPOL specs. Or is it a valid invoice using a CIUS that overrides PEPPOL in weird ways?

**Comment by rycks** [comment]
you are right, is that a peppol invoice ?

```
<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDataty
pes-2" xmlns:ccts="urn:oasis:names:specification:ubl:schema:xsd:CoreComponentPar
ameters-2" xmlns:stat="urn:oasis:names:specification:ubl:schema:xsd:DocumentStat
usCode-1.0" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicC
omponents-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggre
gateComponents-2" xmlns:udt="urn:un:unece:uncefact:data:draft:UnqualifiedDataTyp
esSchemaModule:2" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
>
  <cbc:UBLVersionID>2.0</cbc:UBLVersionID>
  <cbc:CustomizationID>1.0</cbc:CustomizationID>
  <cbc:ProfileID>FFF.BE ExactOnline</cbc:ProfileID>
  <cbc:ID>20700108</cbc:ID>
  <cbc:InvoiceTypeCode listURI="http://www.FFF.be/ubl/2.0/cl/gc/BE-InvoiceCode-1.0.gc">380</cbc:InvoiceTypeCode>
```

what could i do *before* open it with your peppol lib to check if it's a good peppol invoice ?

**Comment by josemmo** [comment]
The UBL snippet you provided appears to have been generated by a software called [Exact Online](https://www.exact.com/software/exact-online) (not a valid EN 16931 invoice).

You can verify this by reading the `<cbc:ProfileID />` field and making sure it starts with "urn:cen.eu:en16931:2017#compliant". For instance, PEPPOL BIS 3.0 invoices here have a value of "urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0".

I'm closing the issue now that this has been clarified.

**Comment by rycks** [comment]
Ok, thanks
but it could be good idea to make a early test in UXML no and get an error or exception in case of XML is not valid ?

**Comment by josemmo** [comment]
Just added proper error handling to throw an `InvalidArgumentException` when the XML document is invalid. You can test it by requiring the latest development version:
```
composer require josemmo/einvoicing:dev-develop
```
