### ISSUE TITLE
Support for BG-30 Line VAT information attributes schemID and schemeAgencyId (NLCIUS v1.0.3)

### ISSUE THREAD

**Issue by cyrildewit** [josemmo/einvoicing#20]
Hi @josemmo,

Thank you for creating this package and publishing it open source. I'm currently dealing with some validation issues with our Peppol partner. I need to set the `schemeID` attribute to `UN/ECE 5153` and `schemeAgencyID` to `6` in the `cac:TaxScheme` node. This is currently not supported by this package and I couldn't extend the package by swapping the instances.

Before I considered creating this issue I tried to get a good grasp of how the ecosystem of einvoices and the available specifications, but the information is quite vague. This support request hopefully makes sense.

It's already possible to set the value of the `cac:TaxScheme`  node:

```php
$invoiceLine = (new InvoiceLine())
    ->setName('Some name')
    ->setPrice(120)
    ->setVatRate(21)
    ->setQuantity(2)
    ->setVatCategory('Z');
```

It is however not possible to set the attribute values of:
* `schemeID`
* `schemeAgencyID`

Some resources:
* https://stpe.semantic-treehouse.nl/#/TreeView/Element_1528564888_00299003
* https://stpe.semantic-treehouse.nl/#/TreeView/Element_1528186302_00158354

I would like to create a pull request for this feature, but since I'm not fully known in this domain I do like to get some feedback on this feature request.

**Comment by josemmo** [comment]
Hi @cyrildewit,

Hmm, this is certainly an interesting problem. The EN 16931 has no mapping for neither the "schemeID" nor "schemeAgencyID" attributes of a tax scheme.

I'm not familiar at all with electronic invoicing in the Netherlands 😅
What's the difference between NLCIUS (the first link you shared) and Invoice v1.2 (the second)?

**Comment by cyrildewit** [comment]
Hi @josemmo,

I couldn't find any documentation about these fields too. Only in previous versions of used invoicing standards in the Netherlands (SI-UBL 1.2 for example). 

The way a CIUS works is that it cannot use UBL features that are not described in the EN 16931 right? So, if for example a CIUS wants to require or use a property on a node it should be described in the specification (EN 16931). Or can a CIUS make non-described properties mandatory? 

About the links. I received them from my consultant after asking him questions about this. I think that the second link is about UBL Invoice v1.2. These properties are part of NLCIUS v1.0.3 according to him. I'm personally a fan of official documentation, but I couldn't find any reference to these properties in the specification. As far as I know, CIUS documents should always cover the differences.

**Comment by josemmo** [comment]
We should think this carefully as more people will benefit from implementing the NLCIUS into the library. Unfortunately, I won't have time to focus on this until the end of May.

If this is a priority for your team, as a quick fix, we could make some methods protected for easy overriding, but I wouldn't create interfaces if there's only one implementation of them in the library.

Ideally, this has to be implemented as a [Preset](https://josemmo.github.io/einvoicing/getting-started/creating-custom-presets/). However, the custom UBL modifications are not yet implemented in the library. IMO, the best we can do is to remove the CII feature from the backlog (to simplify things) and add custom XML-UBL tampering in presets. But again, I have to think this through.

In the meantime, do you know if there's a version of the NLCIUS specification in English? Having example NLCIUS-UBL documents will be awesome.

**Comment by josemmo** [comment]
Hello @cyrildewit,

I finally had time to take a look at this! :)

I checked the [official NLCIUS specification](https://stpe.nl/media/E-Factureren%20-%20Gebruiksinstructie%20voor%20de%20basisfactuur%20v1.0.3.pdf) and couldn't find any mention of "scheme ID" nor "agency ID".
According to the [NLCIUS UBL validator](https://stpe.semantic-treehouse.nl/#/ext/eValidator) from the page you sent, UBL documents without `schemeID="UN/ECE 5153"` are still valid. It makes senses, as there's no reference to `cac:TaxScheme/cbcID/@schemeID` or `cac:TaxScheme/cbcID/@schemeAgencyID` in the [NLCIUS validation rules](https://stpe.semantic-treehouse.nl/api/v1/uploads/SchematronFile_1610968868_00705027/NLCIUS-v1.0.3-rules.sch).

So, the gist is **both attributes are ignored** during validation and the official specification doesn't mention them.

If you still need the attributes, a custom NLCIUS could be implemented. Still, what validation rules is your Peppol partner following?

**Comment by josemmo** [comment]
Closed for inactivity.
