### ISSUE TITLE
Question about BaseQuantity

### ISSUE THREAD

**Issue by KlemenPal** [josemmo/einvoicing#21]
Hi!
Just a question - is there a specific reason why BaseQuantity in InvoiceLine isn't added to the XML if value is 1?
https://github.com/josemmo/einvoicing/blob/967d57e75715729b62b7bec01d8bb339eb1a3ce7/src/Writers/UblWriter.php#L947

**Comment by josemmo** [comment]
Hello @KlemenPal,

Yes, by default the base quantity of an item is 1.  If the `<cbc:BaseQuantity />` UBL element is omitted from a document, it fallbacks to the default value.

By convention, the `<cbc:BaseQuantity />` element is omitted if it has a value of 1.

**Comment by KlemenPal** [comment]
Thanks for the information 👍
