### ISSUE TITLE
Add support for TaxCurrencyCode (BT-6)

### ISSUE THREAD

**Issue by andras-minicrm** [josemmo/einvoicing#22]
Hi @josemmo 

First: thanks for this awesome library!

I'm currently developing integration with anaf (romanian tax authority). They use a special ruleset: **RO_CIUS**
They have a special (fatal) rule:
**BR-RO-030:** If the "Invoice Currency Code" (BT-5) is other than "RON", then the item "VAT Accounting Currency Code" (BT-6) must be "RON".

It seems the library doesn't have a support for BT-6. We've created two xml-s with smartbill I've attached them here. However BT-6 requires an extra:
```
<cac:TaxTotal>
    <cbc:TaxAmount currencyID="RON">93.89</cbc:TaxAmount><!--BT-111-->
</cac:TaxTotal>
```
so BT-6 maybe needs an exchange rate option to correctly calculate the amount (eg: EUR to RON: 4.1234, RON to RON 1.000)?

Samples:
[RON2RON.txt](https://github.com/josemmo/einvoicing/files/8778964/RON2RON.txt)
[EUR2RON.txt](https://github.com/josemmo/einvoicing/files/8778965/EUR2RON.txt)

(these are xmls but github doesn't allow xml uploads)

**Comment by josemmo** [comment]
Hello @andras-minicrm,

Thanks for the feedback! I've implemented the feature, will be merged in the next release.

**Comment by andras-minicrm** [comment]
Amazing, thx!! When the next release scheduled?

**Comment by josemmo** [comment]
We don't have a scheduled release cycle, the next release will be (probably) in June.
