### ISSUE TITLE
Text for Payment Means (BT-82) is bugged?

### ISSUE THREAD

**Issue by andras-minicrm** [josemmo/einvoicing#28]
Hi @josemmo!

it seems setMeansText is generating a wrong xml node:
```php
$payment = new Payment();
$payment->setMeansCode(31);
$payment->setMeansText("Payment Text");
```
this generates the following xml:
```xml
<cac:PaymentMeans>
    <cbc:PaymentMeansCode name="Payment Text">31</cbc:PaymentMeansCode>
</cac:PaymentMeans>
```
instead of:
```xml
<cac:PaymentMeans>
    <cbc:PaymentMeansCode>31</cbc:PaymentMeansCode>
    <cbc:InstructionNote>Payment Text</cbc:InstructionNote>
</cac:PaymentMeans>
```
BT-82 is the InstructionNote, in regards to the documentations.

**Comment by josemmo** [comment]
Hi, @andras-minicrm!

According to the [Peppol BIS specification](https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-PaymentMeans/), that's how BT-81 (payment means type code) and BT-82 (payment means text) should be encoded.

Is this different for another CIUS/extension?

**Comment by andras-minicrm** [comment]
Hi @josemmo!

Probably you are right! I'm working from a document which is based on UBL 2.1.
Based on this validator https://ecosio.com/en/peppol-and-xml-document-validator/

- UBL Invoice 2.1 ruleset both of versions are valid.
- (eg) 16931 option choosed it shows warnings.

I think I've worked from a wrong document.

**Comment by josemmo** [comment]
Yes, EN16931 is the European electronic invoicing specification (which is what this library implements).
UBL was chosen as a language for representing EN16931 invoices in XML, but not all UBL documents are EN16931-compliant.

In this you have more information: https://josemmo.github.io/einvoicing/getting-started/eu-einvoicing-concepts/
