### ISSUE TITLE
decimal rounding number

### ISSUE THREAD

**Issue by CaptainKant** [josemmo/einvoicing#29]
Hi and thank your for your work
I'm currently trying to implement your superb library for Saoudan Arabia rules
I need to set all prices and totals with 2 decimal rounding, is the feature missing or am I missing someting ?

**Comment by josemmo** [comment]
Hi, @CaptainKant!

Yes, decimal rounding is implemented through the [`$invoice->setRoundingMatrix()`](https://josemmo.github.io/einvoicing/reference/invoice/#setroundingmatrix) method. In [this link](https://josemmo.github.io/einvoicing/getting-started/creating-custom-presets/#custom-invoice-modifications) you have more information on how to create a preset with a custom number of decimals.

What CIUS are you trying to implement? Maybe it could be added to the library.

**Comment by CaptainKant** [comment]
Hey
I'm not sure to have undestood what CIUS is, from what I just read it concerns Europe,
In Saudi Arabia, I've got is two xsd files, with custom rules ( for example number of decimals, need a uuid....)
When it will be stable I can share you the modifs I had to do

**Comment by josemmo** [comment]
Closed due to inactivity.

**Comment by CaptainKant** [comment]
CIUS is arabia saoudian rules, and it's EN16931 compliant.
As I said there  I've got is two xsd files, with custom rules ( for example number of decimals, need a uuid....)

**Comment by josemmo** [comment]
Could you share the XSD files?

**Comment by CaptainKant** [comment]
Yes of course
Here they are

https://drive.google.com/file/d/1-G31rWMibc3NGwENpgLJo2PZ-_ju3geW/view?usp=sharing
https://drive.google.com/file/d/1tV2fJXItRvwimCZLKoRCacwFbBbh34rj/view?usp=sharing

Do you want the dirty DomDocument post-processing I've made to match it ?

**Comment by josemmo** [comment]
Hello @CaptainKant,

EN16931-compliant documents must contain a "specification identifier" (BT-24) whose value starts with `urn:cen.eu:en16931:2017#compliant#`.

The specifications you provide don't seem to have a specification identifier at all.

**Comment by CaptainKant** [comment]
Sorry this is all the doc saoudi arabia gouvernement give to devs to implement invoice upon CEN/EN 16931:2017 standard.

Anyway thank you for your library that have helped me a lot, I just needed to add 3 tags to be compliant.
