### ISSUE TITLE
Peppol compliance status and messaging extension

### ISSUE THREAD

**Issue by turbo124** [josemmo/einvoicing#30]
Hi there,

Great library!

Can you advise the current status of compliance with PEPPOL?

We are looking to extend the functionality here to include messaging using something like this implementation here:

https://github.com/everbinding/econnect-psb-php

Happy to collaborate, please let me know how we can get in touch.

**Comment by josemmo** [comment]
Hello @turbo124,

I'm not familiar with this library. Could you explain what's "PSB" and how could it be integrated with einvoicing?

**Comment by turbo124** [comment]
@josemmo 

From my research, creating a PEPPOL invoice is only one step in the process. The einvoice then needs to be passed into the PEPPOL network to the recipient.

This is where a library such as the one above could assist in the transport of these invoices.

**Comment by josemmo** [comment]
I see. Is this something exclusive to PEPPOL? The closest EU specification I could find related to the exchange of documents is [eDelivery](https://ec.europa.eu/digital-building-blocks/wikis/display/DIGITAL/eDelivery).

I still don't see how could this be integrated into this library, to me it looks like a good candidate for a separate project. Are you interested in any specific feature?
