### ISSUE TITLE
Invoice rounding problem

### ISSUE THREAD

**Issue by andras-minicrm** [josemmo/einvoicing#31]
Hi!

It seems there is rounding problem with the xml generator:
**[BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).**

example data input:
```php
$line = new InvoiceLine();
$line->setPrice(0.25)
    ->setQuantity(26935.78)
    ->setVatRate(19)
```

Which generates this nodes:
```xml
<cac:TaxTotal>
<cbc:TaxableAmount currencyID="RON">6733.95</cbc:TaxableAmount>
<cbc:TaxAmount currencyID="RON">1279.45</cbc:TaxAmount>
...
<cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="RON">6733.95</cbc:LineExtensionAmount>
    <cbc:TaxExclusiveAmount currencyID="RON">6733.95</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="RON">8013.39</cbc:TaxInclusiveAmount>
    <cbc:PayableAmount currencyID="RON">8013.39</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
```
The final amounts should be 8013.40, not 8013.39

And here is the generated xml:
[factura-102-o2u-2022-e-ron-00066.txt](https://github.com/josemmo/einvoicing/files/9930644/factura-102-o2u-2022-e-ron-00066.txt)

**Comment by quamis** [comment]
@andras-minicrm 6733,945×1,19=8013,39455. Rounding this will lead to 8013,39. How did you determine it should be 8013.40?

**Comment by andras-minicrm** [comment]
@quamis 

Yea, you are probably right, based on the error message 6733.95 + 1279.45 = (8013.40) should be equal cbc:TaxInclusiveAmount (8013.39) . Probably the TaxAmount should be 1279.44 to get the correct 8013.39 value.

**Comment by josemmo** [comment]
Hello @andras-minicrm,

Hmm, given BR-CO-15 is a Business Rule from the EN 16931, I'm guessing the final roundings performed by this library need to be updated to comply with the standard.

I'll investigate further and prepare a new implementation as soon as I have some spare time.

**Comment by josemmo** [comment]
Hello @andras-minicrm,

This should be fixed now. Give it a try to make sure it works:
```
composer require josemmo/einvoicing:dev-develop
```

**Comment by andras-minicrm** [comment]
Hello @josemmo,

It seems the fix works, thanks!
