### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [josemmo/einvoicing#32]
Hi Josemmo,

Love this package! It seems that there are still some fields missing.
E.g. AccountingCostCode is a field that can be placed in the invoice or invoice lines.

Is it possible to add these fields, or is it perhaps possible to add these using a general function?

Something like 
```
public function setCustomValues(string $fieldName, string $fieldValue) {
        $this->{$fieldName} = $fieldValue;
        return $this;
    }
```

**Comment by josemmo** [comment]
Hello @ThisIsMyFavouriteJar,

What field are you referring to? I cannot find any field with that name in the PEPPOL specification or in EN 16931.
If it's `cbc:AccountingCost`, that's [already implemented](https://josemmo.github.io/einvoicing/reference/invoice-line/#setbuyeraccountingreference).

**Comment by josemmo** [comment]
Closed due to inactivity.
