### ISSUE TITLE
CreditNote support

### ISSUE THREAD

**Issue by quamis** [josemmo/einvoicing#33]
Hello,
From what I'm seeing this package doesn't have support for credit notes?

**Comment by josemmo** [comment]
Hello @quamis,

According to EN 16931, you can do this by setting the document type to `381` (see [this link](https://unece.org/fileadmin/DAM/trade/untdid/d17a/tred/tred1001.htm) for a list of type IDs).

In this library, you can change the document type with the method [`$invoice->setType()`](https://josemmo.github.io/einvoicing/reference/invoice/#settype).

**Comment by quamis** [comment]
Ok, thanks
