### ISSUE TITLE
How to add tag SupplierAssignedAccountID

### ISSUE THREAD

**Issue by jw7712** [josemmo/einvoicing#35]
I'm trying to export UBL invoices for importing in an accounting application (Venice) and need to add cac:AccountingCustomerParty/cbc:SupplierAssignedAccountID to the XML file.

How can this be done using this package?

![Screenshot from 2022-12-05 15-18-22](https://user-images.githubusercontent.com/57006726/208966348-824802b4-23f4-4b4e-a3e8-b63a3f6fcbd2.png)

Thanks in advance

**Comment by josemmo** [comment]
Hello @jw7712,

"cbc:SupplierAssignedAccountID" doesn't appear to be part of the EN 16931 standard nor PEPPOL BIS 3.0.

**Comment by jw7712** [comment]
@josemmo 
Thanks for your reply. I see that indeed it's not part of the standard, but some accounting packages make use of it to match a contact by id.

When searching for it i see that exact online is also using this:
https://support.exactonline.com/community/s/knowledge-base#All-All-HNO-Concept-general-importexport-gen-impexp-ublineolc

**Comment by josemmo** [comment]
Adding this feature is not feasible because is non-standard and, in [some cases](https://docs.peppol.eu/poacc/billing/3.0/rules/UBL-CR-202/), not allowed.

But if you need to add the field to a document, you can do it manually after generating the XML:
```php
use Einvoicing\Invoice;
use Einvoicing\Presets;
use Einvoicing\Writers\UblWriter;
use UXML\UXML;

// Generate invoice
$inv = new Invoice(Presets\Peppol::class);
// [...]

// Export invoice
$writer = new UblWriter();
$xml = UXML::fromString($writer->export($inv));
$xml->get('cac:AccountingCustomerParty')->add('cbc:SupplierAssignedAccountID', '0011223344'); // <---
echo $xml->asXML();
```

**Comment by jw7712** [comment]
Great, thanks for the great support!
I will try it!

The issue can be closed.
