### ISSUE TITLE
XML validator when there is allowance on lines

### ISSUE THREAD

**Issue by rycks** [josemmo/einvoicing#40]
Hello,
here is my problem:

```
Element/context: /:Invoice[1]/cac:InvoiceLine[1]
XPath test: u:slack($lineExtensionAmount, ($quantity * ($priceAmount div $baseQuantity)) + $chargesTotal - $allowancesTotal, 0.02)
Error message: Invoice line net amount MUST equal (Invoiced quantity * (Item net price/item price base quantity) + Sum of invoice line charge amount - sum of invoice line allowance amount
```

My invoice is really basic: only one line:

- price: 100
- quantity: 1
- vat rate: 20%
- discount : 10%

**Comment by josemmo** [comment]
Hello @rycks,

Where are you getting that error message from? Could you provide the XML invoice that's giving you that error?

**Comment by josemmo** [comment]
Thanks for the fix, @rycks!

I (finally) managed to find some time to investigate this issue further and can confirm that there was a bug in the calculation of the amounts for allowances and discounts on invoice lines. PR #41 is correct, I just updated the unit tests to fix the expected values.

Will try to publish a new release with this fix ASAP.
