### ISSUE TITLE
Division by zero for  $invoice->getTotals()->taxInclusiveAmount

### ISSUE THREAD

**Issue by cornelpopa** [josemmo/einvoicing#49]
Division by zero for 
$invoice->getTotals()->taxInclusiveAmount

Invoice is from E.ON Energie ..

i've put xml relevant part bellow.

<cac:LegalMonetaryTotal>
	<cbc:LineExtensionAmount currencyID="RON">0.00</cbc:LineExtensionAmount>
	<cbc:TaxExclusiveAmount currencyID="RON">0.00</cbc:TaxExclusiveAmount>
	<cbc:TaxInclusiveAmount currencyID="RON">0.00</cbc:TaxInclusiveAmount>
	<cbc:PayableRoundingAmount currencyID="RON">0.00</cbc:PayableRoundingAmount>
	<cbc:PayableAmount currencyID="RON">0.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
<cac:InvoiceLine>
	<cbc:ID>1</cbc:ID>
	<cbc:InvoicedQuantity unitCode="EA">2.776</cbc:InvoicedQuantity>
	<cbc:LineExtensionAmount currencyID="RON">4.55</cbc:LineExtensionAmount>
	<cac:Item>
		<cbc:Name>Incarcare electrica - Ianuarie 2024 Conform contract</cbc:Name>
		<cac:ClassifiedTaxCategory>
			<cbc:ID>S</cbc:ID>
			<cbc:Percent>19</cbc:Percent>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:ClassifiedTaxCategory>
	</cac:Item>
	<cac:Price>
		<cbc:PriceAmount currencyID="RON">163.77</cbc:PriceAmount>
		<cbc:BaseQuantity unitCode="C62">0.00</cbc:BaseQuantity>
	</cac:Price>
</cac:InvoiceLine>
<cac:InvoiceLine>
	<cbc:ID>2</cbc:ID>
	<cbc:InvoicedQuantity unitCode="EA">1.000</cbc:InvoicedQuantity>
	<cbc:LineExtensionAmount currencyID="RON">-4.55</cbc:LineExtensionAmount>
	<cac:Item>
		<cbc:Name>Stornare incarcare electrica - Ianuarie 2024 Conform contract</cbc:Name>
		<cac:ClassifiedTaxCategory>
			<cbc:ID>S</cbc:ID>
			<cbc:Percent>19</cbc:Percent>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:ClassifiedTaxCategory>
	</cac:Item>
	<cac:Price>
		<cbc:PriceAmount currencyID="RON">454.62</cbc:PriceAmount>
		<cbc:BaseQuantity unitCode="C62">0.00</cbc:BaseQuantity>
	</cac:Price>
</cac:InvoiceLine>

**Comment by cornelpopa** [comment]
DivisionByZeroError: Division by zero in.../vendor/josemmo/einvoicing/src/InvoiceLine.php:305
Stack trace:
#0 .../vendor/josemmo/einvoicing/src/InvoiceLine.php(343): Einvoicing\InvoiceLine->getNetAmountBeforeAllowancesCharges()
#1 .../vendor/josemmo/einvoicing/src/Models/InvoiceTotals.php(102): Einvoicing\InvoiceLine->getNetAmount()
#2 .../vendor/josemmo/einvoicing/src/Invoice.php(892): Einvoicing\Models\InvoiceTotals::fromInvoice()
#3 .../app/Jobs/MessageDetailsJob.php(54): Einvoicing\Invoice->getTotals()

**Comment by josemmo** [comment]
Hello @cornelpopa,

Thanks for reporting this issue.

I can add a check to avoid the `DivisionByZeroError`, but shouldn't this be the expected behavior? I mean, an InvoiceLine with a base quantity of 0 (zero) doesn't make sense, so the error is appropiate.

Otherwise, what should be the expected return value of `InvoiceLine::getNetAmountBeforeAllowancesCharges()` when the base quantity is zero?

**Comment by cornelpopa** [comment]
@josemmo Yeah, you're right - that line doesn't make sense, and I agree that division by 0 should be checked for and return maybe an Exception? The invoice where I hit the problem was one "received" by me, not generated by me. You can never be assume that data sent by others is proper. :-(

**Comment by josemmo** [comment]
Ok, for now I think is best to keep the current behavior and throw an exception.

**Comment by cornelpopa** [comment]
Great,

Thank you.
