### ISSUE TITLE
Support for Purchase Orders (EN16931 UBL Peppol BIS Ordering)

### ISSUE THREAD

**Issue by onidlo** [josemmo/einvoicing#54]
Dear all,

are there any plans to support Purchase Orders? (EN16931 UBL Peppol BIS Ordering)

It seems quite similar to eInvoice:
![image](https://github.com/josemmo/einvoicing/assets/11643311/ade69b89-3ebd-41b0-b598-a070f2030d15)

**Comment by josemmo** [comment]
Hello @onidlo,

Thanks for your interest.

Purchase orders are currently not in scope for this library, it only focuses on invoices.
