### ISSUE TITLE
Wrong totals?

### ISSUE THREAD

**Issue by cornelpopa** [josemmo/einvoicing#55]
Am I missing something or the totals calculations are wrong in case of negative quantity?

For the bellow xml invoice totals should be 0, and yet.....

Einvoicing\Models\InvoiceTotals {#1982 ▼ // app/Http/Controllers/TestController.php:38
  +currency: "RON"
  +vatCurrency: null
  +netAmount: 472727.02
  +allowancesAmount: 0.0
  +chargesAmount: 0.0
  +vatAmount: 89818.13
  +taxExclusiveAmount: **_472727.02_**
  +taxInclusiveAmount: **_562545.15_**
  +paidAmount: 0.0
  +roundingAmount: 0.0
  +customVatAmount: null
  +payableAmount: 562545.15
  +vatBreakdown: array:1 [▼
    0 => 
Einvoicing\Models
\
VatBreakdown {#1989 ▼
      +category: "S"
      +rate: 19.0
      +exemptionReasonCode: null
      +exemptionReason: null
      +taxableAmount: 472727.02
      +taxAmount: 89818.13
    }
  ]
}

Relevant XML lines...

------------------------------------------------------------------------------
<cac:TaxTotal>
        <cbc:TaxAmount currencyID="RON">0.00</cbc:TaxAmount>
        <cac:TaxSubtotal>
            <cbc:TaxableAmount currencyID="RON">0.00</cbc:TaxableAmount>
            <cbc:TaxAmount currencyID="RON">0.00</cbc:TaxAmount>
            <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>19.00</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:TaxCategory>
        </cac:TaxSubtotal>
    </cac:TaxTotal>
    <cac:LegalMonetaryTotal>
        <cbc:LineExtensionAmount currencyID="RON">0.00</cbc:LineExtensionAmount>
        <cbc:TaxExclusiveAmount currencyID="RON">0.00</cbc:TaxExclusiveAmount>
        <cbc:TaxInclusiveAmount currencyID="RON">0.00</cbc:TaxInclusiveAmount>
        <cbc:AllowanceTotalAmount currencyID="RON">0.00</cbc:AllowanceTotalAmount>
        <cbc:ChargeTotalAmount currencyID="RON">0</cbc:ChargeTotalAmount>
        <cbc:PrepaidAmount currencyID="RON">0</cbc:PrepaidAmount>
        <cbc:PayableRoundingAmount currencyID="RON">0.00</cbc:PayableRoundingAmount>
        <cbc:PayableAmount currencyID="RON">0.00</cbc:PayableAmount>
    </cac:LegalMonetaryTotal>
    <cac:InvoiceLine>
        <cbc:ID>1</cbc:ID>
        <cbc:InvoicedQuantity unitCode="H87">1.0000</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="RON">236363.51</cbc:LineExtensionAmount>
        <cac:Item>
            <cbc:Name>LUCRARI CF. DEVIZ</cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>19.00</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
        <cac:Price>
            <cbc:PriceAmount currencyID="RON">236363.51</cbc:PriceAmount>
            <cbc:BaseQuantity unitCode="H87">1.0000</cbc:BaseQuantity>
        </cac:Price>
    </cac:InvoiceLine>
    <cac:InvoiceLine>
        <cbc:ID>2</cbc:ID>
        <cbc:InvoicedQuantity unitCode="H87">-1.0000</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="RON">-210619.15</cbc:LineExtensionAmount>
        <cac:Item>
            <cbc:Name>STORNO AVANS </cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>19.00</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
        <cac:Price>
            <cbc:PriceAmount currencyID="RON">210619.15</cbc:PriceAmount>
            <cbc:BaseQuantity unitCode="H87">-1.0000</cbc:BaseQuantity>
        </cac:Price>
    </cac:InvoiceLine>
    <cac:InvoiceLine>
        <cbc:ID>3</cbc:ID>
        <cbc:InvoicedQuantity unitCode="H87">-1.0000</cbc:InvoicedQuantity>
        <cbc:LineExtensionAmount currencyID="RON">-25744.36</cbc:LineExtensionAmount>
        <cac:Item>
            <cbc:Name>STORNO PARTIAL AVANS </cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>19.00</cbc:Percent>
                <cac:TaxScheme>
                    <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
        <cac:Price>
            <cbc:PriceAmount currencyID="RON">25744.36</cbc:PriceAmount>
            <cbc:BaseQuantity unitCode="H87">-1.0000</cbc:BaseQuantity>
        </cac:Price>
    </cac:InvoiceLine>

**Comment by josemmo** [comment]
Hello @cornelpopa,

Could you provide the PHP code needed to generate that invoice so that I can reproduce the bug?

**Comment by cornelpopa** [comment]
Hi @josemmo 

Nothing complicated, just importing the above xml.

$reader = new UblReader();
$invoice = $reader->import($xml);

dump($invoice->getTotals());

If needed I can provide the full xml file...

**Comment by josemmo** [comment]
Yes, please provide the XML as an attachment as the pasted code has missing elements.

**Comment by cornelpopa** [comment]
Please find the xml attached.
I've just edited company names/id's... 
[4262108830_edited.zip](https://github.com/josemmo/einvoicing/files/15290632/4262108830_edited.zip)

**Comment by josemmo** [comment]
Hello @cornelpopa,

Sorry for taking this long to reply.

After a thorough look, I can confirm that the library is properly calculating totals. The issue is with the `<cbc:BaseQuantity />` nodes, which have a value of "-1" in the XML document you provide. That doesn't make sense.

Let's have a look at one of the invoice lines:
```xml
<cac:InvoiceLine>
    <!-- [...] -->
    <cbc:InvoicedQuantity unitCode="H87">-1</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="RON">-210619.15</cbc:LineExtensionAmount>
    <cac:Price>
        <cbc:PriceAmount currencyID="RON">210619.15</cbc:PriceAmount>
        <cbc:BaseQuantity unitCode="H87">-1</cbc:BaseQuantity>
    </cac:Price>
</cac:InvoiceLine>
```

In here, you're saying that the price of **minus one item** is 210619.15 RON (this is what doesn't make sense). If you then invoice "-1" items, the line extension amount would be (210619.15 RON × -1) × -1 = 210619.15 RON.

If you replace `<cbc:BaseQuantity>-1</cbc:BaseQuantity>` with `<cbc:BaseQuantity>1</cbc:BaseQuantity>`, then the invoice totals amount to exactly zero.
