### ISSUE TITLE
Chat community

### ISSUE THREAD

**Issue by leonardehrenfried** [josemmo/einvoicing#57]
Hello,

e-invoicing is becoming mandatory in Germany but I'm very confused about all these specifications (EN 16931, XRechnung, Factur-X, Finnvoice, PEPPOL BIS, UBL, CII ...) and to what degree they are supposed to be compatible with each other.

For this reason I'm starting a chat room on Matrix where I would like to build a community of people interested in this topic: 
https://matrix.to/#/#e-invoicing:matrix.org (you can join with a Github account).

Perhaps you're interested in joining.

**Comment by josemmo** [comment]
Thanks for the info, @leonardehrenfried! Will check it out.
