### ISSUE TITLE
How to Do Self Billing Invoicing & Self Billing Credit Notes

### ISSUE THREAD

**Issue by Sivaprasad598** [josemmo/einvoicing#61]
Hi,

Its great Library, i'm implementing peppol invoices using this library. but i stuck at creating self billing Invoice & Credit Note. I Couldn't find or I'm not fully got Knowledge on this how to implement using setType() in Invoice. Could you please help??? 

Thank you

**Comment by josemmo** [comment]
Hi, @Sivaprasad598!

Unfortunately, this library does not support credit notes.
